
FriendIcon = "FriendIcon"
Initialize = "Initialize"
AddFriend = "AddFriend"
AddGroup = "AddGroup"
DeleteFriend = "DeleteFriend"
WithdrawFromGroup = "WithdrawFromGroup"
SendMessage = "SendMessage"
DeleteMessage = "DeleteMessage"
SendImg = "SendImg"
GetRecord = "GetRecord"
RecordImgBack = "RecordImgBack"
Login = "Login"
LoginWithPassword = "LoginWithPassword"
InviteFriend = "InviteFriend"
GetUserData = "GetUserData"
GetUserIcon = "GetUserIcon"
GetAuth = "GetAuth"
AddPoster = "AddPoster"
GetPoster = "GetPoster"
GetPosterReply = "GetPosterReply"
DeletePoster = "DeletePoster"
DeletePosterReply = "DeletePosterReply"
ChangeUserIcon = "ChangeUserIcon"
ChangeUserName = "ChangeUserName"
ChangeUserIntro = "ChangeUserIntro"
ChangeUserPassword = "ChangeUserPassword"
ForwardTXT = "ForwardTXT"
ForwardIMG = "ForwardIMG"
PubAnnoc = "PubAnnoc"
GetAnnoc = "GetAnnoc"
Voting = "Voting"

AddFriendNotification = "AddFriendNotification"

SubmitFCMToken = "SubmitFCMToken"
