
FriendIcon = "FriendIcon"
Initialize = "Initialize"
AddFriend = "AddFriend"
AddGroup = "AddGroup"
DeleteFriend = "DeleteFriend"
WithdrawFromGroup = "WithdrawFromGroup"
SendMessage = "SendMessage"
SendImg = "SendImg"
GetRecord = "GetRecord"
RecordImgBack = "RecordImgBack"
Login = "Login"
InviteFriend = "InviteFriend"
GetUserData = "GetUserData"
GetUserIcon = "GetUserIcon"
GetAuth = "GetAuth"
AddPoster = "AddPoster"
GetPoster = "GetPoster"
GetPosterReply = "GetPosterReply"

AddFriendNotification = "AddFriendNotification"

SubmitFCMToken = "SubmitFCMToken"
